/* Yedeğe giren tablolar ve sütunları. Şifreli sütunlar (şifre, IBAN numarası, dosya numarası, abone numarası) yedeğe girmez. */
export const YEDEK_TABLOLARI: Record<string, string> = {
  kisiler: 'id,olusturma,guncelleme,surum,silindi_at,ad,tur,alt_tur,takma_adlar,telefon,notlar,adres,baro_no',
  ibanlar: 'id,olusturma,guncelleme,surum,silindi_at,sahip_turu,kisi_id,hesap_id,etiket,banka,iban_son4,gecerli',
  icra_dosyalari: 'id,olusturma,guncelleme,surum,silindi_at,eski_id,oncelik,icra_dairesi,alacakli_id,avukat_id,borc_id,taraf_rolu,takip_turu,takip_yolu,ozel_durum,durum,uyap_durum,karsi_taraf,ucuncu_sahislar,son_islemler,diger_haciz_sayisi,faiz_orani,gercek_asil_alacak,guncel_toplam_borc,faiz_tutari,vekalet_ucreti,masraf,vergi,tahsil_harci,toplam_alacak,yatan_para,tahsilat,reddiyat,acilis_tarihi,kapanis_tarihi,son_islem_tarihi,dogrulama_tarihi,tebligat_tarihi,uyap_tarihi',
  ayarlar: 'id,olusturma,guncelleme,surum,silindi_at,anahtar,deger',
  hizli_notlar: 'id,olusturma,guncelleme,surum,silindi_at,metin',
  saglik_gunluk: 'id,olusturma,guncelleme,surum,silindi_at,gun,adim,kalori,su_ml,uyku,tansiyon,nabiz',
  hesaplar: 'id,olusturma,guncelleme,surum,silindi_at,banka_id,ad,tur,para_birimi,acilis_bakiyesi,hesap_kesim_gunu,son_odeme_gunu,aktif,notlar',
  borclar: 'id,olusturma,guncelleme,surum,silindi_at,tur,alt_tur,ad,yon,alacakli_id,hesap_id,anapara,guncel_borc,faiz_orani,baslangic_tarihi,bitis_tarihi,durum,notlar',
  odemeler: 'id,olusturma,guncelleme,surum,silindi_at,borc_id,hesap_id,vade_tarihi,tutar,durum,odeme_tarihi,hareket_id,notlar',
  gelirler: 'id,olusturma,guncelleme,surum,silindi_at,ad,tur,sabit,periyot,tutar,gun,hesap_id,borc_id,baslangic,bitis,aktif,gelir_sayilir,notlar',
  giderler: 'id,olusturma,guncelleme,surum,silindi_at,ad,tur,periyot,tutar,para_birimi,gun,hesap_id,taksit_toplam,taksit_kalan,bitis,aktif,notlar',
  vadeler: 'id,olusturma,guncelleme,surum,silindi_at,yon,gelir_id,gider_id,tarih,tutar,durum,hareket_id',
  varliklar: 'id,olusturma,guncelleme,surum,silindi_at,tur,ad,hesap_id,miktar,birim,anapara,faiz_orani,vade_tarihi,guncel_deger,bilgi',
  limitler: 'id,olusturma,guncelleme,surum,silindi_at,kisi_id,hesap_id,ad,limit_tutari,kullanilan,notlar',
  hareketler: 'id,olusturma,guncelleme,surum,silindi_at,hesap_id,yon,tur,tutar,tarih,kategori,aciklama,gelir_sayilir,odeme_id,vade_id,varlik_id',
  hedefler: 'id,olusturma,guncelleme,surum,silindi_at,ad,grup,hedef_tutar,biriken,hedef_tarihi,durum,notlar',
  istekler: 'id,olusturma,guncelleme,surum,silindi_at,ad,hedef_id,tahmini_tutar,oncelik,baglanti,durum,notlar',
  begeniler: 'id,olusturma,guncelleme,surum,silindi_at,ad,baglanti,fiyat,ilk_fiyat,notlar',
  alinacaklar: 'id,olusturma,guncelleme,surum,silindi_at,ad,hedef_id,tahmini_tutar,hedef_tarih,durum,alindi_tarihi,hareket_id,notlar',
  ajanda_olaylari: 'id,olusturma,guncelleme,surum,silindi_at,baslik,tarih,saat,notlar,tamamlandi',
  todolar: 'id,olusturma,guncelleme,surum,silindi_at,baslik,tarih,oncelik,etiket,tekrar,tamamlandi,tamamlanma,notlar',
  zihin_sayfalari: 'id,olusturma,guncelleme,surum,silindi_at,baslik,ust_id,icerik,sira',
  listeler: 'id,olusturma,guncelleme,surum,silindi_at,ad,kaynak,notlar',
  liste_ogeleri: 'id,olusturma,guncelleme,surum,silindi_at,liste_id,baslik,baglanti,etiket,okundu',
  davalar: 'id,olusturma,guncelleme,surum,silindi_at,tur,mahkeme,konu,asama,durum,dava_degeri,sonraki_durusma,avukat_id,karsi_taraf,icra_id,acilis_tarihi,notlar',
  urunler: 'id,olusturma,guncelleme,surum,silindi_at,ad,birim,kategori,stok_miktari,asgari_stok,son_kullanma',
  fisler: 'id,olusturma,guncelleme,surum,silindi_at,market,tarih,toplam,hesap_id,hareket_id,notlar',
  fis_kalemleri: 'id,olusturma,guncelleme,surum,silindi_at,fis_id,urun_id,miktar,birim_fiyat,tutar',
  alisveris_ogeleri: 'id,olusturma,guncelleme,surum,silindi_at,ad,miktar,birim,urun_id,alindi',
  sifre_hesaplari: 'id,olusturma,guncelleme,surum,silindi_at,hizmet,kategori,adres',
};
